### PR TITLE
Display angle in degrees instead of radians(Fixes #3)

### LINKED ISSUE #3: Rotation in degrees
Now, rotation is displayed and stored in radians.
Instead of radians we should display it in "degrees" because it's more intuitive. 
We can add 2 helper function: rad2deg, deg2rad maybe?

### PR DESCRIPTION
**Pull request by madan96**
#3

### CODE REVIEW

**Comment by alexadam** [comment]
Perfect! But... before merging, could you also change Model -> changeData -> ... if (rotation) ... newValue... to convert back to radians before setting the new state? Sorry if the issue's description wasn't clear enough.

**Comment by madan96** [comment]
I have only changed the radians to degree while printing. I guess the original value still remains to be in radians. Please tell me if  I'm wrong or I'm not able to understand what you are saying.

**Comment by alexadam** [comment]
The value in the input field is linked to the value in the component's state. If you display it in degrees, it will be stored in degrees (when you change it, it calls the changeData method) -> at the next render it will display the value in degrees * 180/math.pi.
So, before setting the new state, convert it back to radians  @ Model -> changeData -> ... if (rotation) ... newValue...

**Comment by alexadam** [comment]
Thanks! ;)

**Pull request merged**
